# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  packageOutput: '$(Build.ArtifactStagingDirectory)'
  packageVersion: '1.0.$(Build.BuildId)'
steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- script: |
    dotnet pack --configuration $(buildConfiguration) --output $(packageOutput) /p:Version=$(packageVersion)
  displayName: 'Generar paquete NuGet'

- script: |
    dotnet nuget push $(packageOutput)/*.nupkg --api-key oy2avwim63m7573s67wa346ylmjhucfupp665bxw7db3mi --source https://api.nuget.org/v3/index.json --skip-duplicate
  displayName: 'Publicar en NuGet'
